//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLyCaoOc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOPDONG
    {
        public CHITIETHOPDONG()
        {
            this.PHIEUGIAHANs = new HashSet<PHIEUGIAHAN>();
        }
    
        public string MaHD { get; set; }
        public string MaPHG { get; set; }
        public Nullable<int> ThoiGianThue { get; set; }
    
        public virtual HOPDONG HOPDONG { get; set; }
        public virtual PHONG PHONG { get; set; }
        public virtual ICollection<PHIEUGIAHAN> PHIEUGIAHANs { get; set; }
    }
}
