//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLyCaoOc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLCAOOCEntities : DbContext
    {
        public QLCAOOCEntities()
            : base("name=QLCAOOCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHITIETHOPDONG> CHITIETHOPDONGs { get; set; }
        public DbSet<CONGTY> CONGTies { get; set; }
        public DbSet<HOPDONG> HOPDONGs { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<PHIEUGIAHAN> PHIEUGIAHANs { get; set; }
        public DbSet<PHONG> PHONGs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TANG> TANGs { get; set; }
        public DbSet<THAMSO> THAMSOes { get; set; }
        public DbSet<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
