<?xml version="1.0" encoding="utf-8"?><Database Name="QLCAOOC" Class="dbQLyCaoOcDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HPHUONG\SQLEXPRESS;Initial Catalog=QLCAOOC;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLCAOOCConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETHOPDONG" Member="CHITIETHOPDONGs">
    <Type Name="CHITIETHOPDONG">
      <Column Name="MaHD" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaPHG" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ThoiGianThue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CHITIETHOPDONG_PHIEUGIAHAN" Member="PHIEUGIAHANs" ThisKey="MaHD,MaPHG" OtherKey="MaHD,MaPHG" Type="PHIEUGIAHAN" />
      <Association Name="HOPDONG_CHITIETHOPDONG" Member="HOPDONG" ThisKey="MaHD" OtherKey="MaHD" Type="HOPDONG" IsForeignKey="true" />
      <Association Name="PHONG_CHITIETHOPDONG" Member="PHONG" ThisKey="MaPHG" OtherKey="MaPHG" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONGTY" Member="CONGTies">
    <Type Name="CONGTY">
      <Column Name="MaCongTy" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChiCT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="MaHD" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="CONGTY_NHANVIEN" Member="NHANVIENs" ThisKey="MaCongTy" OtherKey="MaCongTy" Type="NHANVIEN" />
      <Association Name="HOPDONG_CONGTY" Member="HOPDONG" ThisKey="MaHD" OtherKey="MaHD" Type="HOPDONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOPDONG" Member="HOPDONGs">
    <Type Name="HOPDONG">
      <Column Name="MaHD" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TienCoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOPDONG_CHITIETHOPDONG" Member="CHITIETHOPDONGs" ThisKey="MaHD" OtherKey="MaHD" Type="CHITIETHOPDONG" />
      <Association Name="HOPDONG_CONGTY" Member="CONGTies" ThisKey="MaHD" OtherKey="MaHD" Type="CONGTY" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChiNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDTNV" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MaCongTy" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="MaPHG" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="CONGTY_NHANVIEN" Member="CONGTY" ThisKey="MaCongTy" OtherKey="MaCongTy" Type="CONGTY" IsForeignKey="true" />
      <Association Name="PHONG_NHANVIEN" Member="PHONG" ThisKey="MaPHG" OtherKey="MaPHG" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUGIAHAN" Member="PHIEUGIAHANs">
    <Type Name="PHIEUGIAHAN">
      <Column Name="MaPhieuGiaHan" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayGiaHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaHD" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="MaPHG" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Association Name="CHITIETHOPDONG_PHIEUGIAHAN" Member="CHITIETHOPDONG" ThisKey="MaHD,MaPHG" OtherKey="MaHD,MaPHG" Type="CHITIETHOPDONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONG" Member="PHONGs">
    <Type Name="PHONG">
      <Column Name="MaPHG" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenPHG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DienTich" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PHONG_CHITIETHOPDONG" Member="CHITIETHOPDONGs" ThisKey="MaPHG" OtherKey="MaPHG" Type="CHITIETHOPDONG" />
      <Association Name="PHONG_NHANVIEN" Member="NHANVIENs" ThisKey="MaPHG" OtherKey="MaPHG" Type="NHANVIEN" />
      <Association Name="TANG_PHONG" Member="TANG1" ThisKey="Tang,DienTich" OtherKey="Tang1,DienTich" Type="TANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="MaTK" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TenDN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TANG" Member="TANGs">
    <Type Name="TANG">
      <Column Name="Tang" Member="Tang1" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DienTich" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Gia" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="TANG_PHONG" Member="PHONGs" ThisKey="Tang1,DienTich" OtherKey="Tang,DienTich" Type="PHONG" />
    </Type>
  </Table>
  <Table Name="dbo.THAMSO" Member="THAMSOs">
    <Type Name="THAMSO">
      <Column Name="MaTS" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaTriTS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>