//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLyCaoOc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        public HOPDONG()
        {
            this.CHITIETHOPDONGs = new HashSet<CHITIETHOPDONG>();
            this.CONGTies = new HashSet<CONGTY>();
        }
    
        public string MaHD { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> TienCoc { get; set; }
    
        public virtual ICollection<CHITIETHOPDONG> CHITIETHOPDONGs { get; set; }
        public virtual ICollection<CONGTY> CONGTies { get; set; }
    }
}
