//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLyCaoOc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public string DiaChiNV { get; set; }
        public string SDTNV { get; set; }
        public string MaCongTy { get; set; }
        public string MaPHG { get; set; }
    
        public virtual CONGTY CONGTY { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
