//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLyCaoOc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUGIAHAN
    {
        public string MaPhieuGiaHan { get; set; }
        public Nullable<System.DateTime> NgayGiaHan { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string MaHD { get; set; }
        public string MaPHG { get; set; }
    
        public virtual CHITIETHOPDONG CHITIETHOPDONG { get; set; }
    }
}
