//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLyCaoOc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        public PHONG()
        {
            this.CHITIETHOPDONGs = new HashSet<CHITIETHOPDONG>();
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }
    
        public string MaPHG { get; set; }
        public string TenPHG { get; set; }
        public int Tang { get; set; }
        public int DienTich { get; set; }
    
        public virtual ICollection<CHITIETHOPDONG> CHITIETHOPDONGs { get; set; }
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
        public virtual TANG TANG1 { get; set; }
    }
}
