//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLyCaoOc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TANG
    {
        public TANG()
        {
            this.PHONGs = new HashSet<PHONG>();
        }
    
        public int Tang1 { get; set; }
        public int DienTich { get; set; }
        public string Gia { get; set; }
    
        public virtual ICollection<PHONG> PHONGs { get; set; }
    }
}
